// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: eve/claim/v1beta1/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ClaimAuthorization struct {
	ContractAddress string `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty" yaml:"contract_address"`
	Action          Action `protobuf:"varint,2,opt,name=action,proto3,enum=eve.claim.v1beta1.Action" json:"action,omitempty" yaml:"action"`
}

func (m *ClaimAuthorization) Reset()         { *m = ClaimAuthorization{} }
func (m *ClaimAuthorization) String() string { return proto.CompactTextString(m) }
func (*ClaimAuthorization) ProtoMessage()    {}
func (*ClaimAuthorization) Descriptor() ([]byte, []int) {
	return fileDescriptor_2229279bc5194974, []int{0}
}
func (m *ClaimAuthorization) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClaimAuthorization) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ClaimAuthorization.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ClaimAuthorization) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClaimAuthorization.Merge(m, src)
}
func (m *ClaimAuthorization) XXX_Size() int {
	return m.Size()
}
func (m *ClaimAuthorization) XXX_DiscardUnknown() {
	xxx_messageInfo_ClaimAuthorization.DiscardUnknown(m)
}

var xxx_messageInfo_ClaimAuthorization proto.InternalMessageInfo

func (m *ClaimAuthorization) GetContractAddress() string {
	if m != nil {
		return m.ContractAddress
	}
	return ""
}

func (m *ClaimAuthorization) GetAction() Action {
	if m != nil {
		return m.Action
	}
	return ActionInitialClaim
}

// Params defines the claim module's parameters.
type Params struct {
	AirdropEnabled     bool          `protobuf:"varint,1,opt,name=airdrop_enabled,json=airdropEnabled,proto3" json:"airdrop_enabled,omitempty"`
	AirdropStartTime   time.Time     `protobuf:"bytes,2,opt,name=airdrop_start_time,json=airdropStartTime,proto3,stdtime" json:"airdrop_start_time" yaml:"airdrop_start_time"`
	DurationUntilDecay time.Duration `protobuf:"bytes,3,opt,name=duration_until_decay,json=durationUntilDecay,proto3,stdduration" json:"duration_until_decay,omitempty" yaml:"duration_until_decay"`
	DurationOfDecay    time.Duration `protobuf:"bytes,4,opt,name=duration_of_decay,json=durationOfDecay,proto3,stdduration" json:"duration_of_decay,omitempty" yaml:"duration_of_decay"`
	// denom of claimable asset
	ClaimDenom string `protobuf:"bytes,5,opt,name=claim_denom,json=claimDenom,proto3" json:"claim_denom,omitempty"`
	// list of contracts and their allowed claim actions
	AllowedClaimers []ClaimAuthorization `protobuf:"bytes,6,rep,name=allowed_claimers,json=allowedClaimers,proto3" json:"allowed_claimers" yaml:"allowed_claimers"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_2229279bc5194974, []int{1}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetAirdropEnabled() bool {
	if m != nil {
		return m.AirdropEnabled
	}
	return false
}

func (m *Params) GetAirdropStartTime() time.Time {
	if m != nil {
		return m.AirdropStartTime
	}
	return time.Time{}
}

func (m *Params) GetDurationUntilDecay() time.Duration {
	if m != nil {
		return m.DurationUntilDecay
	}
	return 0
}

func (m *Params) GetDurationOfDecay() time.Duration {
	if m != nil {
		return m.DurationOfDecay
	}
	return 0
}

func (m *Params) GetClaimDenom() string {
	if m != nil {
		return m.ClaimDenom
	}
	return ""
}

func (m *Params) GetAllowedClaimers() []ClaimAuthorization {
	if m != nil {
		return m.AllowedClaimers
	}
	return nil
}

func init() {
	proto.RegisterType((*ClaimAuthorization)(nil), "eve.claim.v1beta1.ClaimAuthorization")
	proto.RegisterType((*Params)(nil), "eve.claim.v1beta1.Params")
}

func init() { proto.RegisterFile("eve/claim/v1beta1/params.proto", fileDescriptor_2229279bc5194974) }

var fileDescriptor_2229279bc5194974 = []byte{
	// 536 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0xbf, 0x6f, 0xd3, 0x4e,
	0x18, 0xc6, 0x73, 0xdf, 0xf6, 0x1b, 0xc1, 0x55, 0x6d, 0x92, 0x53, 0x25, 0x9c, 0x44, 0xb2, 0x23,
	0x8b, 0xaa, 0x19, 0x90, 0xad, 0xa6, 0x5b, 0xb7, 0x38, 0x01, 0x89, 0x09, 0x64, 0x60, 0x61, 0xb1,
	0x2e, 0xf6, 0x25, 0x58, 0xb2, 0x73, 0xd6, 0xf9, 0x12, 0x08, 0x3b, 0x0b, 0x53, 0x27, 0xd4, 0x11,
	0xf1, 0xd7, 0x74, 0xec, 0xc8, 0x64, 0x50, 0xb2, 0x31, 0x66, 0x61, 0x45, 0xf7, 0xc3, 0x20, 0xe2,
	0x48, 0x6c, 0xb9, 0xe7, 0x79, 0xde, 0xf7, 0xfd, 0xe4, 0xcd, 0x1b, 0x68, 0x92, 0x25, 0x71, 0xc3,
	0x04, 0xc7, 0xa9, 0xbb, 0xbc, 0x98, 0x10, 0x8e, 0x2f, 0xdc, 0x0c, 0x33, 0x9c, 0xe6, 0x4e, 0xc6,
	0x28, 0xa7, 0xa8, 0x45, 0x96, 0xc4, 0x91, 0xbe, 0xa3, 0xfd, 0xce, 0xe9, 0x8c, 0xce, 0xa8, 0x74,
	0x5d, 0xf1, 0x49, 0x05, 0x3b, 0xe6, 0x8c, 0xd2, 0x59, 0x42, 0x5c, 0xf9, 0x9a, 0x2c, 0xa6, 0x6e,
	0xb4, 0x60, 0x98, 0xc7, 0x74, 0xae, 0x7d, 0x6b, 0xd7, 0xe7, 0x71, 0x4a, 0x72, 0x8e, 0xd3, 0x4c,
	0x07, 0x1e, 0x56, 0x49, 0xe4, 0x2b, 0x60, 0x24, 0xa4, 0x2c, 0x52, 0x29, 0xfb, 0x0b, 0x80, 0x68,
	0x24, 0xe4, 0xe1, 0x82, 0xbf, 0xa1, 0x2c, 0x7e, 0x2f, 0x67, 0xa0, 0x27, 0xb0, 0x19, 0xd2, 0x39,
	0x67, 0x38, 0xe4, 0x01, 0x8e, 0x22, 0x46, 0xf2, 0xdc, 0x00, 0x3d, 0xd0, 0xbf, 0xef, 0x75, 0xb7,
	0x85, 0xf5, 0x60, 0x85, 0xd3, 0xe4, 0xca, 0xde, 0x4d, 0xd8, 0x7e, 0xa3, 0x94, 0x86, 0x4a, 0x41,
	0x63, 0x58, 0xc7, 0xa1, 0xe8, 0x68, 0xfc, 0xd7, 0x03, 0xfd, 0x93, 0x41, 0xdb, 0xa9, 0x7c, 0x7f,
	0x67, 0x28, 0x03, 0x5e, 0x6b, 0x5b, 0x58, 0xc7, 0xaa, 0xb1, 0x2a, 0xb1, 0x7d, 0x5d, 0x6b, 0xff,
	0x3c, 0x84, 0xf5, 0xe7, 0x72, 0x8b, 0xe8, 0x1c, 0x36, 0x70, 0xcc, 0x22, 0x46, 0xb3, 0x80, 0xcc,
	0xf1, 0x24, 0x21, 0x91, 0xe4, 0xba, 0xe7, 0x9f, 0x68, 0xf9, 0xb1, 0x52, 0x11, 0x85, 0xa8, 0x0c,
	0xe6, 0x1c, 0x33, 0x1e, 0x88, 0xfd, 0x48, 0x8a, 0xa3, 0x41, 0xc7, 0x51, 0xcb, 0x73, 0xca, 0xe5,
	0x39, 0x2f, 0xcb, 0xe5, 0x79, 0x67, 0xb7, 0x85, 0x55, 0xdb, 0x16, 0x56, 0x5b, 0xa3, 0x54, 0x7a,
	0xd8, 0xd7, 0xdf, 0x2c, 0xe0, 0x37, 0xb5, 0xf1, 0x42, 0xe8, 0xa2, 0x1a, 0x7d, 0x02, 0xf0, 0xb4,
	0xfc, 0x8d, 0x82, 0xc5, 0x9c, 0xc7, 0x49, 0x10, 0x91, 0x10, 0xaf, 0x8c, 0x03, 0x39, 0xb3, 0x5d,
	0x99, 0x39, 0xd6, 0x61, 0xef, 0xa9, 0x18, 0xf9, 0xa3, 0xb0, 0xcc, 0x7d, 0xe5, 0x8f, 0x68, 0x1a,
	0x73, 0x92, 0x66, 0x7c, 0xb5, 0x2d, 0xac, 0xae, 0x82, 0xda, 0x97, 0xb3, 0x6f, 0x04, 0x16, 0x2a,
	0xad, 0x57, 0xc2, 0x19, 0x0b, 0x03, 0x7d, 0x04, 0xb0, 0xf5, 0xbb, 0x82, 0x4e, 0x35, 0xd5, 0xe1,
	0xbf, 0xa8, 0x46, 0x9a, 0xaa, 0x5b, 0xa9, 0xfd, 0x0b, 0xc9, 0xd8, 0x41, 0x2a, 0x43, 0x8a, 0xa7,
	0x51, 0xea, 0xcf, 0xa6, 0x0a, 0xc6, 0x82, 0x47, 0xea, 0x0a, 0x23, 0x32, 0xa7, 0xa9, 0xf1, 0xbf,
	0xb8, 0x29, 0x1f, 0x4a, 0x69, 0x2c, 0x14, 0xf4, 0x01, 0xc0, 0x26, 0x4e, 0x12, 0xfa, 0x96, 0x44,
	0x81, 0x94, 0x09, 0xcb, 0x8d, 0x7a, 0xef, 0xa0, 0x7f, 0x34, 0x38, 0xdb, 0x73, 0x3c, 0xd5, 0xdb,
	0xf5, 0x2e, 0x35, 0x78, 0xa5, 0xcd, 0x9f, 0xcb, 0xdd, 0x75, 0x6c, 0xbf, 0xa1, 0xa5, 0x91, 0x56,
	0xae, 0x0e, 0x6f, 0x3e, 0x5b, 0x35, 0xef, 0xfc, 0x76, 0x6d, 0x82, 0xbb, 0xb5, 0x09, 0xbe, 0xaf,
	0x4d, 0x70, 0xbd, 0x31, 0x6b, 0x77, 0x1b, 0xb3, 0xf6, 0x75, 0x63, 0xd6, 0x5e, 0x1f, 0xbf, 0xd3,
	0x7f, 0x2e, 0xbe, 0xca, 0x48, 0x3e, 0xa9, 0xcb, 0x05, 0x5e, 0xfe, 0x0a, 0x00, 0x00, 0xff, 0xff,
	0x3a, 0xc8, 0x1b, 0x44, 0x00, 0x04, 0x00, 0x00,
}

func (m *ClaimAuthorization) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClaimAuthorization) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ClaimAuthorization) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Action != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.Action))
		i--
		dAtA[i] = 0x10
	}
	if len(m.ContractAddress) > 0 {
		i -= len(m.ContractAddress)
		copy(dAtA[i:], m.ContractAddress)
		i = encodeVarintParams(dAtA, i, uint64(len(m.ContractAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AllowedClaimers) > 0 {
		for iNdEx := len(m.AllowedClaimers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AllowedClaimers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.ClaimDenom) > 0 {
		i -= len(m.ClaimDenom)
		copy(dAtA[i:], m.ClaimDenom)
		i = encodeVarintParams(dAtA, i, uint64(len(m.ClaimDenom)))
		i--
		dAtA[i] = 0x2a
	}
	n1, err1 := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.DurationOfDecay, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.DurationOfDecay):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintParams(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x22
	n2, err2 := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.DurationUntilDecay, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.DurationUntilDecay):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintParams(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x1a
	n3, err3 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.AirdropStartTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.AirdropStartTime):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintParams(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0x12
	if m.AirdropEnabled {
		i--
		if m.AirdropEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ClaimAuthorization) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ContractAddress)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.Action != 0 {
		n += 1 + sovParams(uint64(m.Action))
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AirdropEnabled {
		n += 2
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.AirdropStartTime)
	n += 1 + l + sovParams(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.DurationUntilDecay)
	n += 1 + l + sovParams(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.DurationOfDecay)
	n += 1 + l + sovParams(uint64(l))
	l = len(m.ClaimDenom)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if len(m.AllowedClaimers) > 0 {
		for _, e := range m.AllowedClaimers {
			l = e.Size()
			n += 1 + l + sovParams(uint64(l))
		}
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ClaimAuthorization) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClaimAuthorization: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClaimAuthorization: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Action", wireType)
			}
			m.Action = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Action |= Action(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AirdropEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AirdropEnabled = bool(v != 0)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AirdropStartTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.AirdropStartTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DurationUntilDecay", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.DurationUntilDecay, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DurationOfDecay", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.DurationOfDecay, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClaimDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClaimDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowedClaimers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AllowedClaimers = append(m.AllowedClaimers, ClaimAuthorization{})
			if err := m.AllowedClaimers[len(m.AllowedClaimers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
